# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

main:

  # About tab
  - name: About
    weight: 10
  - name: HDR Ecosystem
    pageRef: about/hdr
    weight: 10
    parent: About
  - name: Conference Series
    pageRef: about/series
    weight: 20
    parent: About
  - name: Objectives
    pageRef: about/objectives
    weight: 25
    parent: About
  - name: Code-of-Conduct
    pageRef: /about/coc
    weight: 30
    parent: About
  - name: Organizing Committee
    pageRef: /about/committee
    weight: 30
    parent: About
  - name: Staff
    pageRef: /about/staff
    weight: 30
    parent: About

  # Speakers tab
  - name: Speakers
    weight: 20
  - name: Keynote Speaker
    weight: 10
    pageRef: /speakers/keynote
    parent: Speakers
  - name: Public Lecture
    weight: 10
    pageRef: /speakers/public
    parent: Speakers
  - name: Plenary
    weight: 10
    pageRef: /speakers/plenary
    parent: Speakers

  # Agenda tab
  - name: Agenda
    weight: 30
  - name: At-a-Glance
    weight: 10
    pageRef: agenda/at-a-glance
    parent: Agenda
  - name: Detailed (Indico)
    weight: 10
    pageRef: https://indico.cern.ch/event/1364455/timetable
    parent: Agenda

  # Practical tab
  - name: Practical
    weight: 40
  - name: Venue
    weight: 10
    pageRef: /practical/venue
    parent: Practical
  - name: Getting Here
    weight: 10
    pageRef: /practical/getting-here
    parent: Practical
  - name: Parking
    weight: 10
    pageRef: /practical/parking
    parent: Practical
  - name: Accommodation
    weight: 10
    pageRef: /practical/accommodation
    parent: Practical
  - name: Getting Around
    weight: 10
    pageRef: /practical/getting-around
    parent: Practical
  - name: Restaurants
    weight: 10
    pageRef: /practical/restaurants
    parent: Practical

  # Services tab
  - name: Services
    weight: 50
  - name: Videoconferencing
    weight: 10
    pageRef: /practical/videoconferencing
    parent: Services
  - name: Captioning
    weight: 10
    pageRef: /practical/captioning
    parent: Services
  
  # Registration tab
  - name: Registration
    weight: 60
    pageRef: https://indico.cern.ch/event/1364455/registration

footer:
  - name: Email
    url: mailto:msn@illinois.edu
    pre: email
    weight: 100
  - name: GitHub
    url: https://github.com/HDR-Ecosystem
    pre: github
    weight: 110
  - name: LinkedIn
    url: https://www.linkedin.com/company/a3d3
    pre: linkedin
    weight: 120
  - name: Twitter
    url: https://x.com/a3d3institute
    pre: x-twitter
    weight: 130
  - name: Youtube
    url: https://www.youtube.com/channel/UCozE47hFawTUb4lUhYlQNIQ
    pre: youtube
    weight: 140